create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  business text,
  service text,
  budget text,
  goals text not null,
  status text not null default 'new' check (status in ('new', 'contacted', 'closed')),
  created_at timestamptz not null default now()
);

create index if not exists inquiries_created_at_idx
  on public.inquiries (created_at desc);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  icon text not null default '✦',
  status text not null default 'active' check (status in ('active', 'inactive')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.services
  add column if not exists sort_order integer not null default 0;

create index if not exists services_sort_order_idx
  on public.services (sort_order, created_at);

insert into public.services (name, description, icon, sort_order)
select * from (values
  ('Performance Marketing', 'Paid campaigns designed to bring qualified traffic, leads and sales while keeping performance measurable.', '◈', 1),
  ('Social Media Marketing', 'Strategic content and social campaigns that make your brand more visible, engaging and memorable.', '◎', 2),
  ('SEO & Content', 'Search-focused content and SEO systems that help your business become easier to discover organically.', '⌁', 3),
  ('E-Commerce Growth', 'Conversion-focused strategies that help online stores attract customers and increase revenue.', '□', 4),
  ('Brand Strategy', 'Positioning, messaging and creative direction that help your brand stand apart from the competition.', '✦', 5),
  ('Complete Growth Strategy', 'A complete digital growth system combining strategy, content, advertising and continuous optimization.', '↗', 6)
) as defaults(name, description, icon, sort_order)
where not exists (select 1 from public.services);